### ISSUE TITLE
Invert colors?

### ISSUE THREAD

**Issue by CoenraadS** [zenghongtu/vscode-asciiflow2#1]
Hello

I am using Dark+ (default) vscode theme

![image](https://user-images.githubusercontent.com/5593825/79041848-54e84900-7bf3-11ea-96f8-cd87185ebcba.png)

How to invert the colors so I have white background?

**Comment by cktang88** [comment]
could we have a way to config the primary and background color instead?

**Comment by zenghongtu** [comment]
v0.2.0 support dark theme
